PDV-Generico/Models/ErrorViewModel.cs
namespace PDV_Generico.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PDV-Generico/Models/Funcionario/FuncionarioCadastroModel.cs
namespace PDV_Generico.Models.Funcionario
{
    public class FuncionarioCadastroModel
    {
        public string? id { get; set; }
        public string? nome { get; set; }
        public string? email { get; set; }
        public string? usuario { get; set; }
        public string? senha { get; set; }
        public string? funcao { get; set; }
        public string? telefone { get; set; }
        public string? cpf_cnpj { get; set; }
    }
}

PDV-Generico/Models/Funcionario/FuncionarioLoginModel.cs
namespace PDV_Generico.Models.Funcionario
{
    public class FuncionarioLoginModel
    {
        public string? usuario { get; set; }
        public string? senha { get; set; }
        public string? funcao { get; set; }

        public bool Login()
        {
            FuncionarioLoginModel teste = new FuncionarioLoginModel();
            teste.usuario = "opa";
            teste.senha = "123";

            if (usuario == teste.usuario && senha == teste.senha)
            {
                funcao = "Admin";
                return true;
            }
            return false;
        }
    }
}

PDV-Generico/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using PDV_Generico.Models;
using System.Diagnostics;

namespace PDV_Generico.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
        public IActionResult Venda()
        {
            return View();
        }
        public IActionResult Compra()
        {
            return View();
        }

        public IActionResult Cliente()
        {
            return View();
        }

        public IActionResult Fornecedor()
        {
            return View();
        }
        public IActionResult Estoque()
        {
            return View();
        }

        public IActionResult Conta()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV-Generico/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using PDV_Generico.Models;
using System.Diagnostics;

namespace PDV_Generico.Controllers
{
    public class FuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Venda()
        {
            return View();
        }
        public IActionResult Cliente()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV-Generico/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using PDV_Generico.Models.Funcionario;
using System.Web;

namespace PDV_Generico.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Cadastro()
        {
            return View();
        }
        public IActionResult EsqueciSenha()
        {
            return View();
        }
        [HttpPost]
        public void ChecarLogin(FuncionarioLoginModel funcionario)
        {
            if(funcionario.Login())
            {
                if (funcionario.funcao == "Admin")
                {
                    Response.Redirect("/Admin/Home");
                }
                else
                {
                    Response.Redirect("/Funcionario/Home");
                }
            }
            else
            {
                Response.Redirect("/Login/Login");
            }
        }
    }
}

PDV-Generico/Controllers/PDVController.cs
using Microsoft.AspNetCore.Mvc;
using PDV_Generico.Models;
using System.Diagnostics;

namespace PDV_Generico.Controllers
{
    public class PDVController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Venda()
        {
            return View();
        }
        public IActionResult Compra()
        {
            return View();
        }

        public IActionResult Cliente()
        {
            return View();
        }

        public IActionResult Fornecedor()
        {
            return View();
        }
        public IActionResult Estoque()
        {
            return View();
        }

        public IActionResult Conta()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PDV-Generico/Views/Admin/Cliente.cshtml
@{
    Layout = "_LayoutPDV";
}

<button type="button" class="btn btn-primary">Adicionar</button>
<button type="button" class="btn btn-primary">Atualizar</button>
<button type="button" class="btn btn-primary">Visualizar</button>
<button type="button" class="btn btn-danger">Remover</button>

PDV-Generico/Views/Admin/Compra.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_LayoutPDV";
}

PDV-Generico/Views/Admin/Conta.cshtml
@{
    Layout = "_LayoutPDV";
}

PDV-Generico/Views/Admin/Estoque.cshtml
@{
    Layout = "_LayoutPDV";
}

PDV-Generico/Views/Admin/Fornecedor.cshtml
@{
    Layout = "_LayoutPDV";
}

<button type="button" class="btn btn-primary">Adicionar</button>
<button type="button" class="btn btn-primary">Atualizar</button>
<button type="button" class="btn btn-primary">Visualizar</button>
<button type="button" class="btn btn-danger">Remover</button>

PDV-Generico/Views/Admin/Home.cshtml
@{
    Layout = "_LayoutPDV";
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo ao PDV Genérico</h1>
    <p>Você pode navegar pelas funções pela aba superior!</p>
    <p>Você está logado como administrador!</p>
</div>

PDV-Generico/Views/Admin/Index.cshtml
@{
    Layout = "_LayoutPDV";
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo ao PDV Genérico</h1>
    <p>Você pode navegar pelas funções pela aba superior!</p>
</div>

PDV-Generico/Views/Admin/Venda.cshtml
@{
    Layout = "_LayoutPDV";
}

PDV-Generico/Views/Home/Cliente.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

PDV-Generico/Views/Home/Compra.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

PDV-Generico/Views/Home/Conta.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

PDV-Generico/Views/Home/Estoque.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

PDV-Generico/Views/Home/Fornecedor.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

PDV-Generico/Views/Home/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

<h1>Login em PDV Genérico</h1>

<form asp-area="" asp-controller="PDV" asp-action="Index">
  <label for="user">Usuário:</label>
  <input type="text" id="BxUser" name="BxUser"><br><br>
  <label for="password">Senha:</label>
  <input type="password" id="BxPassword" name="BxPassword"><br><br>
  <input type="submit" value="Entrar">
</form>

<p><a href="url">Esqueci a senha.</a><p>

PDV-Generico/Views/Home/Venda.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}

PDV-Generico/Views/Login/Cadastro.cshtml
@{
    Layout = "_LayoutVazio";
}

<div align="center">
    <h1>Novo usuário</h1>
</div>

<form asp-controller="Login" asp-action="Index" method="post">
    <div class="form-group" align="center">
        <label for="BxUsuario">Usuário</label>
        <input type="text" class="form-control" id="BxUsuario" placeholder="Insira seu usuário" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxSenha">Senha</label>
        <input type="password" class="form-control" id="BxSenha" placeholder="Insira sua senha" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxConfirmarSenha">Confirmar senha</label>
        <input type="password" class="form-control" id="BxConfirmarSenha" placeholder="Insira novamente sua senha" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxEmail">Email</label>
        <input type="email" class="form-control" id="BxEmail" placeholder="Insira seu email" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxConfirmarEmail">Confirmar email</label>
        <input type="email" class="form-control" id="BxConfirmarEmail" placeholder="Insira novamente seu email" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxNome">Nome</label>
        <input type="text" class="form-control" id="BxNome" placeholder="Insira seu nome" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxCpf_Cnpj">CPF ou CNPJ</label>
        <input type="text" class="form-control" id="BxCpf_Cnpj" placeholder="Insira seu cpf/cnpj (somente números)" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxTelefone">Telefone</label>
        <input type="text" class="form-control" id="BxTelefone" placeholder="Insira seu telefone (somente números)" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxFuncao">Função</label>
        <input type="text" class="form-control" id="BxFuncao" placeholder="Insira a função" style="width:30%">
    </div>
    <div align="center" style="margin-top:10px;">
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </div>
</form>

PDV-Generico/Views/Login/EsqueciSenha.cshtml
@{
    Layout = "_LayoutVazio";
}

<div align="center" style="margin-top:20%;">
    <h1>Esqueci a senha</h1>
</div>



<form asp-controller="Login" asp-action="Index" method="post">
    <div class="form-group" align="center">
        <label for="BxUsuario">Usuário</label>
        <input type="text" class="form-control" id="BxUsuario" placeholder="Insira seu usuário" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxCpf">CPF</label>
        <input type="text" class="form-control" id="BxCpf" placeholder="Insira seu cpf" style="width:30%">
    </div>
    <div align="center" style="margin-top:10px;">
        <button type="submit" class="btn btn-primary">Enviar confirmação</button>
    </div>
</form>

PDV-Generico/Views/Login/Login.cshtml
@model PDV_Generico.Models.Funcionario.FuncionarioLoginModel

@{
    Layout = "_LayoutVazio";
    ViewData["Title"] = "Login";
}

<div align="center" style="margin-top:20%;">
    <h1>Login em PDV Genérico</h1>
</div>

<form asp-action="ChecarLogin">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group" align="center">
        <label asp-for="usuario" class="control-label">Usuário</label>
        <input asp-for="usuario" placeholder="Insira seu usuário" style="width:30%" class="form-control"/>
        <span asp-validation-for="usuario" class="text-danger"></span>
    </div>
    <div class="form-group" align="center">
        <label asp-for="senha" class="control-label">Senha</label>
        <input asp-for="senha" input type="password" placeholder="Insira sua senha" style="width:30%" class="form-control"/>
        <span asp-validation-for="senha" class="text-danger"></span>
    </div>
    <div class="form-check" align="center">
        <input type="checkbox" id="BxConectado" align="center">
        <label for="BxConectado" align="center">Manter conectado</label>
    </div>
    <div class="form-group" align="center">
        <input type="submit" value="Logar" class="btn btn-primary" />
    </div>
</form>

<div style="margin-top:10px;" align="center">
    <a asp-action="Login/EsqueciSenha" style="color:black;">Esqueci a senha</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PDV-Generico/Views/Login/NovoUsuario.cshtml
@{
    Layout = "_LayoutVazio";
}

<div align="center">
    <h1>Novo usuário</h1>
</div>

<form asp-controller="Login" asp-action="Index" method="post">
    <div class="form-group" align="center">
        <label for="BxUsuario">Usuário</label>
        <input type="text" class="form-control" id="BxUsuario" placeholder="Insira seu usuário" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxSenha">Senha</label>
        <input type="password" class="form-control" id="BxSenha" placeholder="Insira sua senha" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxConfirmarSenha">Confirmar senha</label>
        <input type="password" class="form-control" id="BxConfirmarSenha" placeholder="Insira novamente sua senha" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxEmail">Email</label>
        <input type="email" class="form-control" id="BxEmail" placeholder="Insira seu email" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxConfirmarEmail">Confirmar email</label>
        <input type="email" class="form-control" id="BxConfirmarEmail" placeholder="Insira novamente seu email" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxNome">Nome</label>
        <input type="text" class="form-control" id="BxNome" placeholder="Insira seu nome" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxCpf_Cnpj">CPF ou CNPJ</label>
        <input type="text" class="form-control" id="BxCpf_Cnpj" placeholder="Insira seu cpf/cnpj (somente números)" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxTelefone">Telefone</label>
        <input type="text" class="form-control" id="BxTelefone" placeholder="Insira seu telefone (somente números)" style="width:30%">
    </div>
    <div class="form-group" align="center">
        <label for="BxFuncao">Função</label>
        <input type="text" class="form-control" id="BxFuncao" placeholder="Insira a função" style="width:30%">
    </div>
    <div align="center" style="margin-top:10px;">
        <button type="submit" class="btn btn-primary">Cadastrar</button>
    </div>
</form>

PDV-Generico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PDV Generico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PDV_Generico.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PDV - Genérico</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Venda">Venda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Compra">Compra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Cliente">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Fornecedor">Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Estoque">Estoque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Conta">Contas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PDV Genérico - <a asp-area="" asp-controller="Home">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PDV-Generico/Views/Shared/_LayoutPDV.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PDV Generico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PDV_Generico.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PDV - Genérico</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Sair</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Venda">Venda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Compra">Compra</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Cliente">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Fornecedor">Fornecedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Estoque">Estoque</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Conta">Contas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Cadastro">Novo usuário</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PDV Genérico - <a asp-area="" asp-controller="Home">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PDV-Generico/Views/Shared/_LayoutVazio.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PDV Generico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PDV_Generico.styles.css" asp-append-version="true" />
</head>
<body style="background-color:#5CACFA;">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>